FROM node:16.19.1
WORKDIR /react
COPY . .
RUN npm install

# FROM node:16.19.1
#
# WORKDIR /app
#
# ENV PATH /app/node_modules/.bin:$PATH
#
# COPY package.json ./
# COPY package-lock.json ./
# RUN npm install --silent
# # RUN npm install react-scripts@3.4.1 -g --silent
#
# # add app
# COPY . ./
#
#
# # start app
# # CMD ["npm", "run", "dev"]
